[theme]
name = "catppuccin-macchiato-red"

[colors]
AlertInfo = "#a6da95"
AlertWarn = "#f5a97f"
AlertError = "#ed8796"
Annotation = "#ed8796"
Base = "#cad3f5"
Guidance = "#939ab7"
Important = "#ed8796"
Title = "#ed8796"
