[theme]
name = "catppuccin-latte-green"

[colors]
AlertInfo = "#40a02b"
AlertWarn = "#fe640b"
AlertError = "#d20f39"
Annotation = "#40a02b"
Base = "#4c4f69"
Guidance = "#7c7f93"
Important = "#d20f39"
Title = "#40a02b"
