[theme]
name = "catppuccin-macchiato-flamingo"

[colors]
AlertInfo = "#a6da95"
AlertWarn = "#f5a97f"
AlertError = "#ed8796"
Annotation = "#f0c6c6"
Base = "#cad3f5"
Guidance = "#939ab7"
Important = "#ed8796"
Title = "#f0c6c6"
