[theme]
name = "catppuccin-macchiato-sky"

[colors]
AlertInfo = "#a6da95"
AlertWarn = "#f5a97f"
AlertError = "#ed8796"
Annotation = "#91d7e3"
Base = "#cad3f5"
Guidance = "#939ab7"
Important = "#ed8796"
Title = "#91d7e3"
