[theme]
name = "catppuccin-latte-maroon"

[colors]
AlertInfo = "#40a02b"
AlertWarn = "#fe640b"
AlertError = "#d20f39"
Annotation = "#e64553"
Base = "#4c4f69"
Guidance = "#7c7f93"
Important = "#d20f39"
Title = "#e64553"
