[theme]
name = "catppuccin-macchiato-sapphire"

[colors]
AlertInfo = "#a6da95"
AlertWarn = "#f5a97f"
AlertError = "#ed8796"
Annotation = "#7dc4e4"
Base = "#cad3f5"
Guidance = "#939ab7"
Important = "#ed8796"
Title = "#7dc4e4"
